// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComE1SmMjBk0c-1Dk0rrJr2pz09wAff9U',
    appId: '1:861520841427:web:9d4d467f4604b65da86226',
    messagingSenderId: '861520841427',
    projectId: 'vision-comapanion',
    authDomain: 'vision-comapanion.firebaseapp.com',
    storageBucket: 'vision-comapanion.firebasestorage.app',
    measurementId: 'G-VC79QVHMHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyTIQO2LfPuj1NnCjJ1eRzoXbvZNsP4g',
    appId: '1:861520841427:android:b6da43289fb91e78a86226',
    messagingSenderId: '861520841427',
    projectId: 'vision-comapanion',
    storageBucket: 'vision-comapanion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo3vEugLoCtbKjQ_IjzhRMbtO_k5mOGWk',
    appId: '1:861520841427:ios:3a3cea6e46993f2ba86226',
    messagingSenderId: '861520841427',
    projectId: 'vision-comapanion',
    storageBucket: 'vision-comapanion.firebasestorage.app',
    androidClientId: '861520841427-fcv8no70cu5ca3sf67ijd8b309217dgp.apps.googleusercontent.com',
    iosClientId: '861520841427-m5boecrqq02e32jltm73k8l6ig5oi1f0.apps.googleusercontent.com',
    iosBundleId: 'com.proxmaq.visionCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo3vEugLoCtbKjQ_IjzhRMbtO_k5mOGWk',
    appId: '1:861520841427:ios:3a3cea6e46993f2ba86226',
    messagingSenderId: '861520841427',
    projectId: 'vision-comapanion',
    storageBucket: 'vision-comapanion.firebasestorage.app',
    androidClientId: '861520841427-fcv8no70cu5ca3sf67ijd8b309217dgp.apps.googleusercontent.com',
    iosClientId: '861520841427-m5boecrqq02e32jltm73k8l6ig5oi1f0.apps.googleusercontent.com',
    iosBundleId: 'com.proxmaq.visionCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyComE1SmMjBk0c-1Dk0rrJr2pz09wAff9U',
    appId: '1:861520841427:web:7c78c7dfee0975dba86226',
    messagingSenderId: '861520841427',
    projectId: 'vision-comapanion',
    authDomain: 'vision-comapanion.firebaseapp.com',
    storageBucket: 'vision-comapanion.firebasestorage.app',
    measurementId: 'G-QLZ74DLHL9',
  );
}
